"""init schema

Revision ID: 4024f1b3b80e
Revises: 
Create Date: 2026-10-01 19:21:31.149980

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '4024f1b3b80e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_index('ix_audit_log_ws_time', 'audit_log', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('knowledge_doc',
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('doc_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('checksum', sa.CHAR(length=64), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_doc')),
    sa.UniqueConstraint('doc_code', name=op.f('uq_knowledge_doc_doc_code'))
    )
    op.create_index(op.f('ix_knowledge_doc_workspace_id'), 'knowledge_doc', ['workspace_id'], unique=False)
    op.create_table('system_setting',
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('setting_key', name=op.f('pk_system_setting'))
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('workspace',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace')),
    sa.UniqueConstraint('code', name=op.f('uq_workspace_code'))
    )
    op.create_table('workspace_member',
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('invited_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_member')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_ws_user')
    )
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('carrier',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('service_level', sa.String(length=16), server_default='NORMAL', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_carrier_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carrier')),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_carrier_ws_code')
    )
    op.create_index(op.f('ix_carrier_workspace_id'), 'carrier', ['workspace_id'], unique=False)
    op.create_table('customer',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=16), server_default='NORMAL', nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('notify_pref', sa.String(length=32), server_default='MANUAL_COPY', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_customer_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_customer_ws_code')
    )
    op.create_index(op.f('ix_customer_workspace_id'), 'customer', ['workspace_id'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('doc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_no', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.CHAR(length=64), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_doc.id'], name=op.f('fk_knowledge_chunk_doc_id_knowledge_doc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunk'))
    )
    op.create_index(op.f('ix_knowledge_chunk_doc_id'), 'knowledge_chunk', ['doc_id'], unique=False)
    op.create_table('sla_rule',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_value', sa.String(length=32), nullable=True),
    sa.Column('deadline_offset_hours', sa.Integer(), nullable=False),
    sa.Column('max_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action_policy_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_sla_rule_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_rule')),
    sa.UniqueConstraint('workspace_id', 'scope_type', 'scope_value', name='uq_sla_rule_ws_scope')
    )
    op.create_index(op.f('ix_sla_rule_workspace_id'), 'sla_rule', ['workspace_id'], unique=False)
    op.create_table('driver',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('carrier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('license_no', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='AVAILABLE', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], name=op.f('fk_driver_carrier_id_carrier')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_driver_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver'))
    )
    op.create_index(op.f('ix_driver_workspace_id'), 'driver', ['workspace_id'], unique=False)
    op.create_table('vehicle',
    sa.Column('plate_no', sa.String(length=16), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('capacity_ton', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carrier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='IDLE', nullable=False),
    sa.Column('current_driver_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('current_city', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], name=op.f('fk_vehicle_carrier_id_carrier')),
    sa.ForeignKeyConstraint(['current_driver_id'], ['driver.id'], name=op.f('fk_vehicle_current_driver_id_driver')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_vehicle_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle')),
    sa.UniqueConstraint('workspace_id', 'plate_no', name='uq_vehicle_ws_plate')
    )
    op.create_index(op.f('ix_vehicle_workspace_id'), 'vehicle', ['workspace_id'], unique=False)
    op.create_table('order',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('carrier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('vehicle_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('driver_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('origin_city', sa.String(length=64), nullable=False),
    sa.Column('dest_city', sa.String(length=64), nullable=False),
    sa.Column('cargo_desc', sa.String(length=128), nullable=True),
    sa.Column('weight_ton', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='CREATED', nullable=False),
    sa.Column('sla_rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('promised_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('original_eta_at', sa.DateTime(), nullable=True),
    sa.Column('current_eta_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], name=op.f('fk_order_carrier_id_carrier')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_order_customer_id_customer')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('fk_order_driver_id_driver')),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rule.id'], name=op.f('fk_order_sla_rule_id_sla_rule')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_order_vehicle_id_vehicle')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_order_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    sa.UniqueConstraint('workspace_id', 'order_no', name='uq_order_ws_order_no')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_workspace_id'), 'order', ['workspace_id'], unique=False)
    op.create_table('exception_case',
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('carrier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_by', sa.String(length=16), nullable=False),
    sa.Column('detection_rule', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('stall_since', sa.DateTime(), nullable=True),
    sa.Column('root_cause_code', sa.String(length=32), nullable=True),
    sa.Column('root_cause_note', sa.String(length=255), nullable=True),
    sa.Column('impact_summary', sa.String(length=255), nullable=True),
    sa.Column('promised_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('current_eta_at', sa.DateTime(), nullable=True),
    sa.Column('expected_eta_at', sa.DateTime(), nullable=True),
    sa.Column('sla_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_factors_json', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('merged_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], name=op.f('fk_exception_case_carrier_id_carrier')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_exception_case_customer_id_customer')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_exception_case_order_id_order')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_exception_case_vehicle_id_vehicle')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_exception_case_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_case')),
    sa.UniqueConstraint('workspace_id', 'case_no', name='uq_exception_case_ws_case_no')
    )
    op.create_index('ix_exception_case_breach', 'exception_case', ['workspace_id', 'sla_breached', 'created_at'], unique=False)
    op.create_index('ix_exception_case_order', 'exception_case', ['workspace_id', 'order_id'], unique=False)
    op.create_index(op.f('ix_exception_case_status'), 'exception_case', ['status'], unique=False)
    op.create_index(op.f('ix_exception_case_workspace_id'), 'exception_case', ['workspace_id'], unique=False)
    op.create_index('ix_exception_case_ws_status_level', 'exception_case', ['workspace_id', 'status', 'level'], unique=False)
    op.create_table('tracking_event',
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='MOCK', nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_tracking_event_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_event'))
    )
    op.create_index(op.f('ix_tracking_event_occurred_at'), 'tracking_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_tracking_event_order_id'), 'tracking_event', ['order_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_workspace_id'), 'tracking_event', ['workspace_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('analysis_no', sa.String(length=40), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('triggered_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('input_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('risk_level_calculated', sa.String(length=16), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('reused_from_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_replay', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_ai_analysis_exception_id_exception_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_ai_analysis_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis')),
    sa.UniqueConstraint('analysis_no', name=op.f('uq_ai_analysis_analysis_no'))
    )
    op.create_index('ix_ai_analysis_case_time', 'ai_analysis', ['workspace_id', 'exception_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_input_hash'), 'ai_analysis', ['input_hash'], unique=False)
    op.create_index(op.f('ix_ai_analysis_workspace_id'), 'ai_analysis', ['workspace_id'], unique=False)
    op.create_table('carrier_message',
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sender_name', sa.String(length=64), nullable=True),
    sa.Column('sender_role', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parse_result_json', sa.JSON(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('parse_error', sa.String(length=255), nullable=True),
    sa.Column('attachment_urls_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_carrier_message_exception_id_exception_case')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_carrier_message_order_id_order')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_carrier_message_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carrier_message'))
    )
    op.create_index(op.f('ix_carrier_message_exception_id'), 'carrier_message', ['exception_id'], unique=False)
    op.create_index(op.f('ix_carrier_message_order_id'), 'carrier_message', ['order_id'], unique=False)
    op.create_index(op.f('ix_carrier_message_workspace_id'), 'carrier_message', ['workspace_id'], unique=False)
    op.create_table('exception_event',
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_exception_event_exception_id_exception_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_event'))
    )
    op.create_index('ix_exception_event_case_time', 'exception_event', ['exception_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_exception_event_occurred_at'), 'exception_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_exception_event_workspace_id'), 'exception_event', ['workspace_id'], unique=False)
    op.create_table('followup_task',
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('assignee_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='OPEN', nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_approval_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('done_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_followup_task_exception_id_exception_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_followup_task_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followup_task'))
    )
    op.create_index(op.f('ix_followup_task_exception_id'), 'followup_task', ['exception_id'], unique=False)
    op.create_index(op.f('ix_followup_task_workspace_id'), 'followup_task', ['workspace_id'], unique=False)
    op.create_table('notification',
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_draft_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('approved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('source_approval_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_notification_customer_id_customer')),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_notification_exception_id_exception_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_notification_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_exception_id'), 'notification', ['exception_id'], unique=False)
    op.create_index(op.f('ix_notification_workspace_id'), 'notification', ['workspace_id'], unique=False)
    op.create_table('ai_analysis_step',
    sa.Column('analysis_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=16), nullable=False),
    sa.Column('tool_name', sa.String(length=32), nullable=True),
    sa.Column('args_json', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_ai_analysis_step_analysis_id_ai_analysis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis_step'))
    )
    op.create_index(op.f('ix_ai_analysis_step_analysis_id'), 'ai_analysis_step', ['analysis_id'], unique=False)
    op.create_table('approval',
    sa.Column('exception_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('analysis_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action_type', sa.String(length=24), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=True),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ai_payload_json', sa.JSON(), nullable=False),
    sa.Column('final_payload_json', sa.JSON(), nullable=True),
    sa.Column('diff_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('decided_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result_json', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_approval_analysis_id_ai_analysis')),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_case.id'], name=op.f('fk_approval_exception_id_exception_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_approval_workspace_id_workspace'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    op.create_index('ix_approval_case_status', 'approval', ['exception_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_workspace_id'), 'approval', ['workspace_id'], unique=False)
    op.create_index('ix_approval_ws_status', 'approval', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###

    # MySQL 中文全文索引（ngram）；其他方言跳过，检索自动退化为 LIKE（见 KnowledgeRepository.search_chunks）
    if op.get_bind().dialect.name == "mysql":
        op.execute(
            "ALTER TABLE knowledge_chunk "
            "ADD FULLTEXT INDEX ft_knowledge_chunk_content (content) WITH PARSER ngram"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "mysql":
        op.execute("ALTER TABLE knowledge_chunk DROP INDEX ft_knowledge_chunk_content")
    op.drop_index('ix_approval_ws_status', table_name='approval')
    op.drop_index(op.f('ix_approval_workspace_id'), table_name='approval')
    op.drop_index('ix_approval_case_status', table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_ai_analysis_step_analysis_id'), table_name='ai_analysis_step')
    op.drop_table('ai_analysis_step')
    op.drop_index(op.f('ix_notification_workspace_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_exception_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_followup_task_workspace_id'), table_name='followup_task')
    op.drop_index(op.f('ix_followup_task_exception_id'), table_name='followup_task')
    op.drop_table('followup_task')
    op.drop_index(op.f('ix_exception_event_workspace_id'), table_name='exception_event')
    op.drop_index(op.f('ix_exception_event_occurred_at'), table_name='exception_event')
    op.drop_index('ix_exception_event_case_time', table_name='exception_event')
    op.drop_table('exception_event')
    op.drop_index(op.f('ix_carrier_message_workspace_id'), table_name='carrier_message')
    op.drop_index(op.f('ix_carrier_message_order_id'), table_name='carrier_message')
    op.drop_index(op.f('ix_carrier_message_exception_id'), table_name='carrier_message')
    op.drop_table('carrier_message')
    op.drop_index(op.f('ix_ai_analysis_workspace_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_input_hash'), table_name='ai_analysis')
    op.drop_index('ix_ai_analysis_case_time', table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_tracking_event_workspace_id'), table_name='tracking_event')
    op.drop_index(op.f('ix_tracking_event_order_id'), table_name='tracking_event')
    op.drop_index(op.f('ix_tracking_event_occurred_at'), table_name='tracking_event')
    op.drop_table('tracking_event')
    op.drop_index('ix_exception_case_ws_status_level', table_name='exception_case')
    op.drop_index(op.f('ix_exception_case_workspace_id'), table_name='exception_case')
    op.drop_index(op.f('ix_exception_case_status'), table_name='exception_case')
    op.drop_index('ix_exception_case_order', table_name='exception_case')
    op.drop_index('ix_exception_case_breach', table_name='exception_case')
    op.drop_table('exception_case')
    op.drop_index(op.f('ix_order_workspace_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_vehicle_workspace_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_driver_workspace_id'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_sla_rule_workspace_id'), table_name='sla_rule')
    op.drop_table('sla_rule')
    op.drop_index(op.f('ix_knowledge_chunk_doc_id'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index(op.f('ix_customer_workspace_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_carrier_workspace_id'), table_name='carrier')
    op.drop_table('carrier')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_table('workspace')
    op.drop_table('user')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_knowledge_doc_workspace_id'), table_name='knowledge_doc')
    op.drop_table('knowledge_doc')
    op.drop_index('ix_audit_log_ws_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_resource', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
