"""vehicle current_driver unique

Revision ID: 831510b93e08
Revises: 4024f1b3b80e
Create Date: 2026-10-02 20:56:54.816115

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '831510b93e08'
down_revision: str | None = '4024f1b3b80e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_vehicle_current_driver', 'vehicle', ['current_driver_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vehicle_current_driver', table_name='vehicle')
    # ### end Alembic commands ###
